services:
  postgres:
    image: postgres:15
    container_name: streamers_bd

    environment:
      POSTGRES_USER: streamer_user
      POSTGRES_PASSWORD: streamer_pass
      POSTGRES_DB: streamers_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
