-- Moedas principais usadas pelos paises cadastrados.
INSERT INTO Conversao (moeda, nome, fator_conver) VALUES
('USD', 'Dólar Americano', 1.0000),
('EUR', 'Euro', 1.0900),
('BRL', 'Real Brasileiro', 0.1900),
('GBP', 'Libra Esterlina', 1.2700),
('JPY', 'Iene Japonês', 0.0067),
('CAD', 'Dólar Canadense', 0.7400),
('AUD', 'Dólar Australiano', 0.6600),
('CHF', 'Franco Suíço', 1.1400),
('CNY', 'Yuan Chinês', 0.1400),
('MXN', 'Peso Mexicano', 0.0580),
('KRW', 'Won Sul-Coreano', 0.00075),
('INR', 'Rúpia Indiana', 0.0120),
('RUB', 'Rublo Russo', 0.0110),
('TRY', 'Lira Turca', 0.0320),
('ZAR', 'Rand Sul-Africano', 0.0530),
('SGD', 'Dólar de Singapura', 0.7400),
('NZD', 'Dólar Neozelandês', 0.6100),
('SEK', 'Coroa Sueca', 0.0950),
('NOK', 'Coroa Norueguesa', 0.0940),
('DKK', 'Coroa Dinamarquesa', 0.1460);

-- Moedas artificiais apenas para completar o minimo de 100 linhas da tabela.
INSERT INTO Conversao (moeda, nome, fator_conver)
SELECT
    'MOE' || gs,
    'Moeda Artificial ' || gs,
    0.5000 + (gs * 0.0010)
FROM generate_series(1, 80) AS gs;

-- Paises usados como origem/residencia nas outras tabelas.
INSERT INTO Pais (DDI, nome, moeda) VALUES
(1, 'Estados Unidos', 'USD'),
(55, 'Brasil', 'BRL'),
(44, 'Reino Unido', 'GBP'),
(81, 'Japão', 'JPY'),
(33, 'França', 'EUR'),
(49, 'Alemanha', 'EUR'),
(34, 'Espanha', 'EUR'),
(39, 'Itália', 'EUR'),
(7, 'Rússia', 'RUB'),
(86, 'China', 'CNY'),
(91, 'Índia', 'INR'),
(61, 'Austrália', 'AUD'),
(52, 'México', 'MXN'),
(82, 'Coreia do Sul', 'KRW'),
(31, 'Holanda', 'EUR'),
(46, 'Suécia', 'SEK'),
(41, 'Suíça', 'CHF'),
(47, 'Noruega', 'NOK'),
(45, 'Dinamarca', 'DKK'),
(358, 'Finlândia', 'EUR'),
(32, 'Bélgica', 'EUR'),
(43, 'Áustria', 'EUR'),
(351, 'Portugal', 'EUR'),
(30, 'Grécia', 'EUR'),
(48, 'Polônia', 'EUR'),
(420, 'República Tcheca', 'EUR'),
(36, 'Hungria', 'EUR'),
(40, 'Romênia', 'EUR'),
(90, 'Turquia', 'TRY'),
(966, 'Arábia Saudita', 'USD'),
(971, 'Emirados Árabes', 'USD'),
(65, 'Singapura', 'SGD'),
(60, 'Malásia', 'USD'),
(66, 'Tailândia', 'USD'),
(84, 'Vietnã', 'USD'),
(62, 'Indonésia', 'USD'),
(63, 'Filipinas', 'USD'),
(27, 'África do Sul', 'ZAR'),
(234, 'Nigéria', 'USD'),
(20, 'Egito', 'USD'),
(212, 'Marrocos', 'USD'),
(54, 'Argentina', 'USD'),
(56, 'Chile', 'USD'),
(57, 'Colômbia', 'USD'),
(58, 'Venezuela', 'USD'),
(507, 'Panamá', 'USD'),
(503, 'El Salvador', 'USD'),
(502, 'Guatemala', 'USD'),
(505, 'Nicarágua', 'USD'),
(506, 'Costa Rica', 'USD'),
(64, 'Nova Zelândia', 'NZD'),
(372, 'Estônia', 'EUR'),
(371, 'Letônia', 'EUR'),
(370, 'Lituânia', 'EUR'),
(353, 'Irlanda', 'EUR'),
(352, 'Luxemburgo', 'EUR'),
(356, 'Malta', 'EUR'),
(386, 'Eslovênia', 'EUR'),
(421, 'Eslováquia', 'EUR'),
(387, 'Bósnia', 'EUR'),
(381, 'Sérvia', 'EUR'),
(385, 'Croácia', 'EUR'),
(359, 'Bulgária', 'EUR'),
(355, 'Albânia', 'EUR'),
(389, 'Macedônia', 'EUR'),
(382, 'Montenegro', 'EUR'),
(377, 'Mônaco', 'EUR'),
(378, 'San Marino', 'EUR'),
(379, 'Vaticano', 'EUR'),
(350, 'Gibraltar', 'GBP'),
(500, 'Ilhas Malvinas', 'GBP'),
(590, 'Guadalupe', 'EUR'),
(596, 'Martinica', 'EUR'),
(594, 'Guiana Francesa', 'EUR'),
(262, 'Reunião', 'EUR'),
(508, 'Saint Pierre', 'EUR'),
(681, 'Wallis', 'EUR'),
(687, 'Nova Caledônia', 'EUR'),
(689, 'Polinésia', 'EUR'),
(852, 'Hong Kong', 'USD'),
(853, 'Macau', 'USD'),
(886, 'Taiwan', 'USD'),
(673, 'Brunei', 'SGD'),
(670, 'Timor Leste', 'USD'),
(856, 'Laos', 'USD'),
(855, 'Camboja', 'USD'),
(95, 'Myanmar', 'USD'),
(880, 'Bangladesh', 'USD'),
(94, 'Sri Lanka', 'USD'),
(977, 'Nepal', 'USD'),
(975, 'Butão', 'USD'),
(92, 'Paquistão', 'USD'),
(93, 'Afeganistão', 'USD'),
(98, 'Irã', 'USD'),
(964, 'Iraque', 'USD'),
(962, 'Jordânia', 'USD'),
(961, 'Líbano', 'USD'),
(963, 'Síria', 'USD'),
(972, 'Israel', 'USD'),
(970, 'Palestina', 'USD'),
(968, 'Omã', 'USD'),
(974, 'Qatar', 'USD'),
(965, 'Kuwait', 'USD'),
(973, 'Bahrein', 'USD');

-- Empresas usadas como plataformas, patrocinadores e responsaveis.
INSERT INTO Empresa (nome, nome_fantasia) VALUES
('Google LLC', 'Google'),
('Amazon.com Inc', 'Amazon'),
('Microsoft Corporation', 'Microsoft'),
('Tencent Holdings Ltd', 'Tencent'),
('Meta Platforms Inc', 'Meta'),
('Apple Inc', 'Apple'),
('Netflix Inc', 'Netflix'),
('Spotify AB', 'Spotify'),
('Twitter Inc', 'X'),
('Reddit Inc', 'Reddit'),
('Discord Inc', 'Discord'),
('Electronic Arts', 'EA'),
('Activision Blizzard', 'Activision'),
('Nintendo Co Ltd', 'Nintendo'),
('Sony Corporation', 'Sony'),
('Ubisoft Entertainment', 'Ubisoft'),
('Epic Games Inc', 'Epic Games'),
('Valve Corporation', 'Valve'),
('Riot Games Inc', 'Riot'),
('Blizzard Entertainment', 'Blizzard'),
('Twitch Interactive', 'Twitch'),
('YouTube LLC', 'YouTube'),
('TikTok Inc', 'TikTok'),
('Snap Inc', 'Snapchat'),
('Patreon Inc', 'Patreon'),
('PayPal Holdings Inc', 'PayPal'),
('Stripe Inc', 'Stripe'),
('Coinbase Global Inc', 'Coinbase'),
('Visa Inc', 'Visa'),
('Mastercard Inc', 'Mastercard'),
('Samsung Electronics', 'Samsung'),
('LG Corporation', 'LG'),
('Hyundai Group', 'Hyundai'),
('Kakao Corp', 'Kakao'),
('Naver Corporation', 'Naver'),
('Coupang Inc', 'Coupang'),
('Rakuten Inc', 'Rakuten'),
('MercadoLibre Inc', 'MercadoLibre'),
('Shopee Inc', 'Shopee'),
('Alibaba Group', 'Alibaba'),
('Baidu Inc', 'Baidu'),
('JD.com Inc', 'JD'),
('ByteDance Ltd', 'ByteDance'),
('Xiaomi Corporation', 'Xiaomi'),
('Huawei Technologies', 'Huawei'),
('ZTE Corporation', 'ZTE'),
('Lenovo Group', 'Lenovo'),
('ASUS Tek Computer', 'ASUS'),
('Acer Inc', 'Acer'),
('MSI Computer Corp', 'MSI'),
('Gigabyte Technology', 'Gigabyte'),
('Razer Inc', 'Razer'),
('Logitech International', 'Logitech'),
('Corsair Gaming', 'Corsair'),
('SteelSeries', 'SteelSeries'),
('HyperX', 'HyperX'),
('Kingston Technology', 'Kingston'),
('Seagate Technology', 'Seagate'),
('Western Digital', 'WD'),
('Intel Corporation', 'Intel'),
('AMD Inc', 'AMD'),
('NVIDIA Corporation', 'NVIDIA'),
('Qualcomm Inc', 'Qualcomm'),
('Broadcom Inc', 'Broadcom'),
('Texas Instruments', 'TI'),
('Adobe Inc', 'Adobe'),
('Salesforce Inc', 'Salesforce'),
('Oracle Corporation', 'Oracle'),
('SAP SE', 'SAP'),
('IBM Corporation', 'IBM'),
('Cisco Systems', 'Cisco'),
('HP Inc', 'HP'),
('Dell Technologies', 'Dell'),
('EMC Corporation', 'EMC'),
('VMware Inc', 'VMware'),
('ServiceNow Inc', 'ServiceNow'),
('Workday Inc', 'Workday'),
('Atlassian Corp', 'Atlassian'),
('GitHub Inc', 'GitHub'),
('GitLab Inc', 'GitLab'),
('DigitalOcean Inc', 'DigitalOcean'),
('Cloudflare Inc', 'Cloudflare'),
('Akamai Technologies', 'Akamai'),
('Fastly Inc', 'Fastly'),
('Shopify Inc', 'Shopify'),
('Square Inc', 'Square'),
('Block Inc', 'Block'),
('Robinhood Markets', 'Robinhood'),
('Nubank', 'Nubank'),
('StoneCo Ltd', 'Stone'),
('PagSeguro', 'PagSeguro'),
('EBANX', 'EBANX'),
('Adyen NV', 'Adyen'),
('Klarna Bank', 'Klarna'),
('Revolut Ltd', 'Revolut'),
('Monzo Bank', 'Monzo'),
('Starling Bank', 'Starling'),
('N26 Bank', 'N26'),
('TransferWise', 'Wise'),
('Airbnb Inc', 'Airbnb'),
('Uber Technologies', 'Uber'),
('Lyft Inc', 'Lyft'),
('DoorDash Inc', 'DoorDash');
